### ISSUE TITLE
Sculk Sensor Recipe doesn’t work.

### ISSUE THREAD

**Issue by mikaboshikami** [Affehund/ForgottenRecipes#1]
The mod allows me to craft everything other than the skulk sensor which im not sure why. I have looked at the recipe many times and tried it. It doesn't work.

**Comment by Affehund** [comment]
Hey! 
Are you sure you use 2 twisting vines, 2 warped wart blocks and 2 crying obsidians? For me the recipe works. 
If it still doesn't work, feel free to reply.

**Comment by mikaboshikami** [comment]
> Hey!
> Are you sure you use 2 twisting vines, 2 warped wart blocks and 2 crying obsidians? For me the recipe works.
> If it still doesn't work, feel free to reply.

Yeah I used the recipe that the image showed, every recipe worked except the skulk sensor though. 
![image](https://user-images.githubusercontent.com/79607904/125700576-96204ee5-2280-426a-bddd-2909b89b7e83.png)
I did that recipe but it didn't work. Is it because I use 1.17.1 or is it supposed to work on that aswell?

**Comment by Affehund** [comment]
Hu? That's very strange. I tried on 1.17 and 1.17.1 and it works for me. 
Do you use the mod in a modpack? Do you use Roughly Enough Items? With rei you should be able to see the recipe. 
Maybe you can take some screenshots and tell some more details?

**Comment by mikaboshikami** [comment]
I'm not sure. The Rei mod didn't show me the crafting recipes for any of the items of the mod. It may be a glitch though. I'm not sure i'm gonna test it tomorrow again to see.

**Comment by mikaboshikami** [comment]
Oh, it worked this time! I think I know why know, I had another datapack installed which also adds a craftable skulk sensor since I couldn't find a recipe on the RUI mod. I am sorry if this "bug" wasted you're time. I wasn't sure but thank you for providing answers and help though!
